language: python
sudo: false
python:
- 2.7
- 3.4
- 3.5

install:
- pip install -U pip
- pip install -U setuptools pytest
- pip install -U \
    `python -c 'from setup import META; print(" ".join(META["extras_require"]["testing"] + META["install_requires"]))'`

script: make test

notifications:
  irc: "irc.freenode.net#tiddlyweb"
